import {
  StaffWorkReport,
  StaffInvitationRecord,
  StaffSessionRecord,
} from './rbac';

export const DEFAULT_WORK_REPORTS: StaffWorkReport[] = [
  {
    id: 'REP-1405-01',
    staffId: 'STF-01',
    staffName: 'کیوان دادگر',
    staffRole: 'owner',
    reportDate: '2026-09-23',
    shiftType: 'full_day',
    completedSummary: 'نظارت بر تسویه هفتگی درگاه‌های پرداخت، تایید پیش‌نویس قرارداد تامین پارچه با نساجی تاروپود اصفهان، و بازبینی شاخص‌های انبار.',
    ongoingWork: 'بررسی تقویم راه‌اندازی کمپین پاییزه شاه‌پوش و دراپ تیشرت‌های نستعلیق طلاکوب.',
    blockedItems: 'منتظر استعلام قیمت نهایی روبان‌های طلاکوب جعبه هاردباکس تبریز.',
    notes: 'همه فرآیندهای مالی و استرداد وجه مطابق پروتکل دو مرحله‌ای بررسی شدند.',
    submittedAt: '2026-09-23T10:45:00.000Z',
    isSelfEntered: true,
    linkedActionCount: 6,
    pendingAssignmentsCount: 1,
  },
  {
    id: 'REP-1405-02',
    staffId: 'STF-04',
    staffName: 'وحید رضوانی',
    staffRole: 'production',
    reportDate: '2026-09-23',
    shiftType: 'morning',
    completedSummary: 'کالیبراسیون نازل سفید Brother GTX Pro، انجام ۴۸ چرخه چاپ مستقیم DTG روی پنبه ۲۴۰ گرم بدون پرتی و ضایعات، کنترل دمای پرس حرارتی روی ۱۶۵ درجه.',
    ongoingWork: 'آماده‌سازی سری دوم هودی‌های دورس سنگین برای سفارش‌های فوری.',
    blockedItems: 'ندارد (جوهر CMYK و کوتینگ رزین تامین است).',
    notes: 'دستگاه شماره ۲ پس از ۵۰ چرخه شستشوی اتوماتیک هد را با موفقیت گذراند.',
    submittedAt: '2026-09-23T11:15:00.000Z',
    isSelfEntered: true,
    linkedActionCount: 14,
    pendingAssignmentsCount: 3,
  },
  {
    id: 'REP-1405-03',
    staffId: 'STF-02',
    staffName: 'سهراب زارع',
    staffRole: 'production',
    reportDate: '2026-09-23',
    shiftType: 'morning',
    completedSummary: 'داوری و تایید ۱۸ فایل وکتور ارسالی مشتریان، اصلاح تراز کالیگرافی سفارش SHP-1405-882103 در آتلیه و انتقال به صف چاپ.',
    ongoingWork: 'بررسی ۲ فایل با رزولوشن لب مرزی (۱۵۰ DPI) و تماس جهت ارسال نسخه برداری SVG.',
    blockedItems: 'منتظر پاسخ خریدار سفارش SHP-1405-882115 برای شفاف‌سازی رنگ زمینه.',
    notes: 'خطوط راهنمای چاپ ۳۸۰ میلی‌متری به طور کامل با الگوی لباس همپوشانی دارند.',
    submittedAt: '2026-09-23T11:30:00.000Z',
    isSelfEntered: true,
    linkedActionCount: 9,
    pendingAssignmentsCount: 2,
  },
  {
    id: 'REP-1405-04',
    staffId: 'STF-06',
    staffName: 'مریم باطنی',
    staffRole: 'finance',
    reportDate: '2026-09-23',
    shiftType: 'morning',
    completedSummary: 'انطباق ۱۲ سند واریز شاپرک با سفارش‌های پرداخت‌شده، پردازش استرداد وجه سفارش SHP-1405-882103 و آزادسازی تراز رزرو.',
    ongoingWork: 'پاسخگویی به ۲ تیکت پشتیبانی مربوط به پیگیری کد رهگیری پست پیشتاز.',
    notes: 'تسویه حساب هفتگی بانک سامان با مغایرت صفر بسته شد.',
    submittedAt: '2026-09-23T11:50:00.000Z',
    isSelfEntered: true,
    linkedActionCount: 8,
    pendingAssignmentsCount: 1,
  },
  {
    id: 'REP-1405-05',
    staffId: 'STF-05',
    staffName: 'امید فرهمند',
    staffRole: 'inventory',
    reportDate: '2026-09-23',
    shiftType: 'morning',
    completedSummary: 'شمارش موجودی فیزیکی سایزهای L و XL تیشرت‌های اورسایز مشکی، ثبت رسید ورود محموله پارچه خام بافندگی اصفهان در سامانه انبارداری.',
    ongoingWork: 'بسته‌بندی هاردباکس‌های شیفت صبح جهت تحویل به پیک اختصاصی تهران.',
    notes: 'موجودی قفسه A3 با کارتکس سیستم مطابقت ۱۰۰ درصدی دارد.',
    submittedAt: '2026-09-23T11:55:00.000Z',
    isSelfEntered: true,
    linkedActionCount: 7,
    pendingAssignmentsCount: 2,
  },
];

export const DEFAULT_STAFF_INVITATIONS: StaffInvitationRecord[] = [
  {
    id: 'INV-101',
    fullName: 'کامران یزدانی',
    email: 'yazdani.print@gmail.com',
    role: 'production',
    invitedBy: 'کیوان دادگر (بنیان‌گذار)',
    invitedAt: '2026-09-22T14:00:00.000Z',
    status: 'pending_demo_acceptance',
    demoToken: 'DEMO-INV-TOKEN-9941',
    isDemoInvitation: true,
  },
  {
    id: 'INV-102',
    fullName: 'شیما موحد',
    email: 'movahed.support@shahpoosh.ir',
    role: 'support',
    invitedBy: 'کیوان دادگر (بنیان‌گذار)',
    invitedAt: '2026-09-21T09:30:00.000Z',
    status: 'activated',
    demoToken: 'DEMO-INV-TOKEN-9932',
    isDemoInvitation: true,
  },
];

export const DEFAULT_STAFF_SESSIONS: StaffSessionRecord[] = [
  {
    id: 'SES-901',
    staffId: 'STF-01',
    staffName: 'کیوان دادگر',
    role: 'owner',
    ipAddress: '5.160.**.** (Tehran, Iran)',
    device: 'Apple MacBook Pro M3 Max',
    browser: 'Chrome 128 / macOS',
    startedAt: '2026-09-23T08:15:00.000Z',
    isSyntheticDemoSession: true,
    status: 'active',
  },
  {
    id: 'SES-902',
    staffId: 'STF-04',
    staffName: 'وحید رضوانی',
    role: 'production',
    ipAddress: '2.144.**.** (Workshop LAN)',
    device: 'Dell Industrial Workstation',
    browser: 'Firefox 130 / Ubuntu',
    startedAt: '2026-09-23T07:45:00.000Z',
    isSyntheticDemoSession: true,
    status: 'active',
  },
  {
    id: 'SES-903',
    staffId: 'STF-02',
    staffName: 'سهراب زارع',
    role: 'production',
    ipAddress: '5.160.**.** (Studio Wi-Fi)',
    device: 'Apple iMac 27" 5K',
    browser: 'Safari 18 / macOS',
    startedAt: '2026-09-23T08:30:00.000Z',
    isSyntheticDemoSession: true,
    status: 'active',
  },
  {
    id: 'SES-904',
    staffId: 'STF-06',
    staffName: 'مریم باطنی',
    role: 'finance',
    ipAddress: '91.98.**.** (Finance Desk)',
    device: 'ThinkPad T14',
    browser: 'Edge 128 / Windows 11',
    startedAt: '2026-09-23T09:00:00.000Z',
    isSyntheticDemoSession: true,
    status: 'active',
  },
  {
    id: 'SES-905',
    staffId: 'STF-05',
    staffName: 'امید فرهمند',
    role: 'inventory',
    ipAddress: '2.144.**.** (Warehouse Terminal)',
    device: 'Zebra Rugged Tablet',
    browser: 'Chrome Mobile / Android',
    startedAt: '2026-09-23T08:00:00.000Z',
    isSyntheticDemoSession: true,
    status: 'active',
  },
];
