import { AdminNavGroupDef, AdminRouteDef } from './types';

export const ADMIN_GROUPS: AdminNavGroupDef[] = [
  {
    id: 'overview',
    titleFa: 'نمای کلی و خلاصه',
    titleEn: 'Overview',
    iconName: 'LayoutDashboard',
    routes: [
      {
        id: 'dashboard',
        path: '/admin/overview/dashboard',
        groupId: 'overview',
        titleFa: 'داشبورد عملیات کارگاه',
        titleEn: 'Dashboard',
        shortTitleFa: 'داشبورد',
        descriptionFa: 'شاخص‌های کلیدی عملکرد، خلاصه فروش بلادرنگ، وضعیت خطوط چاپ و ناوردایی‌های انبار',
        iconName: 'LayoutGrid',
      },
      {
        id: 'action-center',
        path: '/admin/overview/action-center',
        groupId: 'overview',
        titleFa: 'مرکز اقدام فوری و هشدارهای بحرانی',
        titleEn: 'Action Center',
        shortTitleFa: 'اقدام فوری',
        descriptionFa: 'فهرست اقدامات معوق، طرح‌های نیازمند بازبینی و هشدارهای کسری موجودی بحرانی',
        iconName: 'Zap',
        badgeKey: 'pendingDesigns',
      },
      {
        id: 'work-report',
        path: '/admin/overview/work-report',
        groupId: 'overview',
        titleFa: 'گزارش شیفت کاری و تولید روزانه',
        titleEn: 'Work Report',
        shortTitleFa: 'گزارش شیفت',
        descriptionFa: 'خلاصه تیراژ چاپ، عملکرد اپراتورها، مصرف جوهر نساجی و قطعات بسته‌بندی شده',
        iconName: 'FileSpreadsheet',
      },
    ],
  },
  {
    id: 'sales',
    titleFa: 'فروش و سفارشات',
    titleEn: 'Sales',
    iconName: 'ShoppingBag',
    routes: [
      {
        id: 'orders',
        path: '/admin/sales/orders',
        groupId: 'sales',
        titleFa: 'مدیریت و پردازش سفارش‌ها',
        titleEn: 'Orders',
        shortTitleFa: 'سفارش‌ها',
        descriptionFa: 'فهرست فاکتورها، سبد سفارش‌های تاییدشده، سفارش‌های شخصی‌سازی شده و تغییر مرحله',
        iconName: 'ShoppingBag',
        badgeKey: 'pendingOrders',
        quickAction: {
          label: 'ثبت سفارش دستی',
          actionKey: 'create_order',
        },
      },
      {
        id: 'payments',
        path: '/admin/sales/payments',
        groupId: 'sales',
        titleFa: 'تراکنش‌ها و تسویه درگاه‌های بانکی',
        titleEn: 'Payments',
        shortTitleFa: 'تراکنش‌ها',
        descriptionFa: 'رهگیری پرداخت‌های شاپرک، شماره‌های پیگیری، رسیدها و مبالغ معلق بانکی',
        iconName: 'CreditCard',
        allowedRoles: ['super_admin', 'support_finance'],
        badgeKey: 'unverifiedPayments',
      },
      {
        id: 'shipping',
        path: '/admin/sales/shipping',
        groupId: 'sales',
        titleFa: 'ارسال مرسولات و صدور بارنامه',
        titleEn: 'Shipping',
        shortTitleFa: 'مرسولات و بارنامه',
        descriptionFa: 'کدهای رهگیری پست پیشتاز، تیپاکس، ناوگان پیک اختصاصی تهران و بسته‌بندی',
        iconName: 'Truck',
        allowedRoles: ['super_admin', 'production_operator', 'support_finance'],
      },
      {
        id: 'returns',
        path: '/admin/sales/returns',
        groupId: 'sales',
        titleFa: 'مرجوعی‌ها و استرداد وجه فاکتور',
        titleEn: 'Returns',
        shortTitleFa: 'مرجوعی و استرداد',
        descriptionFa: 'مدیریت پرونده‌های مرجوعی، بازگشت کالا به انبار و صدور سند مالی بستانکار',
        iconName: 'RotateCcw',
        allowedRoles: ['super_admin', 'support_finance'],
      },
      {
        id: 'sales-analytics',
        path: '/admin/sales/analytics',
        groupId: 'sales',
        titleFa: 'تحلیل مالی و روند فروش ناخالص و خالص',
        titleEn: 'Sales Analytics',
        shortTitleFa: 'تحلیل فروش',
        descriptionFa: 'نمودارهای مقایسه‌ای درآمد، میانگین ارزش فاکتور (AOV) و پرفروش‌ترین سایزها',
        iconName: 'TrendingUp',
      },
    ],
  },
  {
    id: 'catalog',
    titleFa: 'کاتالوگ و انبارداری',
    titleEn: 'Catalog',
    iconName: 'Layers',
    routes: [
      {
        id: 'products',
        path: '/admin/catalog/products',
        groupId: 'catalog',
        titleFa: 'محصولات پایه و فرم‌های لباس',
        titleEn: 'Products',
        shortTitleFa: 'محصولات پایه',
        descriptionFa: 'مدل‌های تیشرت اورسایز، کلاسیک، هودی ۳۸۰ گرم، کراپ و پارچه‌های خام پنبه سوپر',
        iconName: 'Tag',
      },
      {
        id: 'variants',
        path: '/admin/catalog/variants',
        groupId: 'catalog',
        titleFa: 'تنوع‌های انبار و کدهای شناسایی (SKUs)',
        titleEn: 'Variants',
        shortTitleFa: 'تنوع‌ها (SKU)',
        descriptionFa: 'تفکیک ماتریس ۱۶۸ کد محصول بر اساس رنگ‌بندی، سایزبندی و آرت‌نامبر انبارداری',
        iconName: 'Grid',
      },
      {
        id: 'inventory',
        path: '/admin/catalog/inventory',
        groupId: 'catalog',
        titleFa: 'موجودی انبار، رزروها و انبارگردانی',
        titleEn: 'Inventory',
        shortTitleFa: 'انبار و کسری',
        descriptionFa: 'تنظیم دستی موجودی با رعایت گارد ناوردایی نامنفی و هشدارهای شارژ مجدد',
        iconName: 'Box',
        badgeKey: 'lowStock',
        allowedRoles: ['super_admin', 'production_operator'],
      },
      {
        id: 'categories',
        path: '/admin/catalog/categories',
        groupId: 'catalog',
        titleFa: 'دسته‌بندی‌ها و شاخه‌ها',
        titleEn: 'Categories',
        shortTitleFa: 'دسته‌بندی‌ها',
        descriptionFa: 'مدیریت تگ‌های کالیگرافی، مینیمال، تایپوگرافی معاصر و معماری کاتالوگ',
        iconName: 'FolderTree',
      },
      {
        id: 'collections',
        path: '/admin/catalog/collections',
        groupId: 'catalog',
        titleFa: 'کلکسیون‌ها و دراپ‌های فصلی',
        titleEn: 'Collections',
        shortTitleFa: 'کلکسیون‌ها',
        descriptionFa: 'کلکسیون اختصاصی شاه‌نشین، دراپ پاییزه دماوند و مجموعه‌های لیمیتد ادیشن',
        iconName: 'Sparkles',
      },
      {
        id: 'media',
        path: '/admin/catalog/media',
        groupId: 'catalog',
        titleFa: 'کتابخانه رسانه‌ها و تصاویر استودیو',
        titleEn: 'Media Library',
        shortTitleFa: 'رسانه‌ها',
        descriptionFa: 'مدیریت شات‌های استودیویی، تصاویر بافت پارچه، موکاپ‌ها و متادیتاهای سئو',
        iconName: 'Image',
      },
      {
        id: 'stock-movements',
        path: '/admin/catalog/stock-movements',
        groupId: 'catalog',
        titleFa: 'دفتر روزنامه گردش انبار و رخدادها',
        titleEn: 'Stock Movements',
        shortTitleFa: 'گردش انبار',
        descriptionFa: 'ثبت و حسابرسی تمامی ورودی‌ها، حواله‌های سفارش، ضایعات و انبارگردانی',
        iconName: 'History',
        allowedRoles: ['super_admin', 'production_operator'],
      },
      {
        id: 'suppliers',
        path: '/admin/catalog/suppliers',
        groupId: 'catalog',
        titleFa: 'تامین‌کنندگان پارچه و مواد مصرفی چاپ',
        titleEn: 'Suppliers',
        shortTitleFa: 'تامین‌کنندگان',
        descriptionFa: 'کارخانجات بافندگی پنبه اصفهان، واردکنندگان جوهر برادر (Brother) و کاغذ ترانسفر',
        iconName: 'Factory',
        allowedRoles: ['super_admin', 'production_operator'],
      },
      {
        id: 'purchase-orders',
        path: '/admin/catalog/purchase-orders',
        groupId: 'catalog',
        titleFa: 'سفارش‌های خرید و رسید انبار (PO)',
        titleEn: 'Purchase Orders',
        shortTitleFa: 'سفارش‌های خرید',
        descriptionFa: 'مدیریت پیش‌نویس، تایید خرید، صدور رسید انبار و انطباق با کسری مواد',
        iconName: 'Receipt',
        allowedRoles: ['super_admin', 'production_operator', 'support_finance'],
      },
    ],
  },
  {
    id: 'custom_studio',
    titleFa: 'آتلیه چاپ سفارشی (POD)',
    titleEn: 'Custom Studio',
    iconName: 'Palette',
    routes: [
      {
        id: 'submissions',
        path: '/admin/custom-studio/submissions',
        groupId: 'custom_studio',
        titleFa: 'درخواست‌های دریافتی از طراح آنلاین',
        titleEn: 'Submissions',
        shortTitleFa: 'درخواست‌های جدید',
        descriptionFa: 'طرح‌های بارگذاری شده توسط خریداران، کالیگرافی‌های اختصاصی و فایل‌های خام',
        iconName: 'UploadCloud',
        badgeKey: 'pendingDesigns',
      },
      {
        id: 'approval',
        path: '/admin/custom-studio/approval',
        groupId: 'custom_studio',
        titleFa: 'داوری فنی آتلیه و اعتبارسنجی رزولوشن',
        titleEn: 'Approval',
        shortTitleFa: 'داوری و تایید طرح',
        descriptionFa: 'بررسی DPI، ترانسپارنسی، حاشیه برش و ارسال طرح به صف پرینتر مستقیم صنعتی',
        iconName: 'FileCheck',
        allowedRoles: ['super_admin', 'designer_reviewer'],
        badgeKey: 'pendingDesigns',
      },
      {
        id: 'artwork',
        path: '/admin/custom-studio/artwork',
        groupId: 'custom_studio',
        titleFa: 'آرشیو فایل‌های برداری و موکاپ‌ها',
        titleEn: 'Artwork',
        shortTitleFa: 'آرشیو آرت‌ورک',
        descriptionFa: 'کتابخانه تایپوگرافی‌های نستعلیق و شکسته، موکاپ‌های نوری و پالت‌های رنگی CMYK',
        iconName: 'Image',
      },
      {
        id: 'production',
        path: '/admin/custom-studio/production',
        groupId: 'custom_studio',
        titleFa: 'خط تولید و پرینترهای مستقیم نساجی (DTG)',
        titleEn: 'Production',
        shortTitleFa: 'خط چاپ DTG',
        descriptionFa: 'مانیتورینگ دستگاه Brother GTX، حرارت پرس کانوایر و آماده‌سازی زیرلایه سفید',
        iconName: 'Printer',
        allowedRoles: ['super_admin', 'production_operator'],
      },
      {
        id: 'qc',
        path: '/admin/custom-studio/qc',
        groupId: 'custom_studio',
        titleFa: 'آزمون کنترل کیفیت نهایی و ثبات شستشو',
        titleEn: 'QC',
        shortTitleFa: 'کنترل کیفیت (QC)',
        descriptionFa: 'تست کشش چاپ، دوخت یقه‌گیر، بسته‌بندی لوکس جعبه مشکی و الصاق شناسنامه اصالت',
        iconName: 'ShieldCheck',
        allowedRoles: ['super_admin', 'production_operator'],
      },
    ],
  },
  {
    id: 'customers',
    titleFa: 'مشتریان و وفاداری',
    titleEn: 'Customers',
    iconName: 'Users',
    routes: [
      {
        id: 'directory',
        path: '/admin/customers/directory',
        groupId: 'customers',
        titleFa: 'فهرست خریداران و باشگاه مشتریان',
        titleEn: 'Directory',
        shortTitleFa: 'فهرست مشتریان',
        descriptionFa: 'پایگاه مشتریان ثبت‌شده، رده‌های طلایی، نقره‌ای و میزان خریدهای تجمعی',
        iconName: 'Contact2',
      },
      {
        id: 'profiles',
        path: '/admin/customers/profiles',
        groupId: 'customers',
        titleFa: 'پرونده تفصیلی و تاریخچه سفارش‌های کاربر',
        titleEn: 'Profiles',
        shortTitleFa: 'پرونده مشتری',
        descriptionFa: 'تاریخچه سبدهای خرید، طرح‌های سفارشی ذخیره شده و نشانی‌های ارسال پستی',
        iconName: 'UserCheck',
      },
      {
        id: 'support',
        path: '/admin/customers/support',
        groupId: 'customers',
        titleFa: 'پشتیبانی، تیکت‌ها و مکاتبات کارگاه',
        titleEn: 'Support',
        shortTitleFa: 'پشتیبانی و تیکت',
        descriptionFa: 'استعلام زمان تحویل، هماهنگی اصلاح طرح‌های گرافیکی و پیگیری مرسولات پستی',
        iconName: 'Headphones',
        allowedRoles: ['super_admin', 'support_finance'],
      },
      {
        id: 'reviews',
        path: '/admin/customers/reviews',
        groupId: 'customers',
        titleFa: 'نظرات، امتیازها و تایید بازخوردها',
        titleEn: 'Reviews',
        shortTitleFa: 'نظرات و دیدگاه‌ها',
        descriptionFa: 'بررسی تصاویر تن‌خور ارسالی کاربران، تایید نظرات برای نمایش در ویترین فروشگاه',
        iconName: 'Star',
      },
    ],
  },
  {
    id: 'analytics',
    titleFa: 'آمار و تحلیل داده‌ها',
    titleEn: 'Analytics',
    iconName: 'BarChart3',
    routes: [
      {
        id: 'sales-analytics',
        path: '/admin/analytics/sales',
        groupId: 'analytics',
        titleFa: 'تحلیل مالی، درآمد و شاخص‌های اقتصادی فروش',
        titleEn: 'Sales & Financials',
        shortTitleFa: 'تحلیل مالی و فروش',
        descriptionFa: 'پایش تفکیکی فروش ناخالص، خالص، تخفیف‌ها، استردادها، بهای تمام‌شده و حاشیه سود',
        iconName: 'TrendingUp',
      },
      {
        id: 'traffic',
        path: '/admin/analytics/traffic',
        groupId: 'analytics',
        titleFa: 'ترافیک روزانه، کاربران یکتا و نشست‌ها',
        titleEn: 'Traffic',
        shortTitleFa: 'ترافیک و بازدید',
        descriptionFa: 'بررسی سلسله‌مراتب بازدیدها، نرخ پرش، میانگین زمان حضور و دستگاه‌های موبایل/دسکتاپ',
        iconName: 'Activity',
      },
      {
        id: 'geography',
        path: '/admin/analytics/geography',
        groupId: 'analytics',
        titleFa: 'توزیع استانی و جغرافیایی سفارش‌ها',
        titleEn: 'Geography',
        shortTitleFa: 'توزیع جغرافیایی',
        descriptionFa: 'تفکیک فروش بر اساس استان‌های تهران، اصفهان، خراسان، فارس، تبریز و شهرهای دیگر',
        iconName: 'MapPin',
      },
      {
        id: 'acquisition',
        path: '/admin/analytics/acquisition',
        groupId: 'analytics',
        titleFa: 'کانال‌های جذب مشتری و رفرال‌ها',
        titleEn: 'Acquisition',
        shortTitleFa: 'کانال‌های جذب',
        descriptionFa: 'آمار ورودی از اینستاگرام شاه‌پوش، جستجوی ارگانیک گوگل، ارجاع مستقیم و کمپین‌ها',
        iconName: 'Share2',
      },
      {
        id: 'conversion',
        path: '/admin/analytics/conversion',
        groupId: 'analytics',
        titleFa: 'قیف نرخ تبدیل (Funnel Conversion)',
        titleEn: 'Conversion',
        shortTitleFa: 'قیف تبدیل',
        descriptionFa: 'رهگیری مسیر کاربر از بازدید صفحه، ورود به طراح سفارشی، افزودن به سبد تا تسویه',
        iconName: 'Filter',
      },
      {
        id: 'campaigns',
        path: '/admin/analytics/campaigns',
        groupId: 'analytics',
        titleFa: 'کمپین‌های فصلی و کدهای تخفیف',
        titleEn: 'Campaigns',
        shortTitleFa: 'کمپین‌های تخفیف',
        descriptionFa: 'نرخ استفاده از کدهای تخفیف جشن‌های پاییزه و بازدهی فروش فلاش‌سیل (Flash Sale)',
        iconName: 'Sparkles',
      },
    ],
  },
  {
    id: 'team',
    titleFa: 'تیم و منابع انسانی کارگاه',
    titleEn: 'Team',
    iconName: 'Shield',
    routes: [
      {
        id: 'tasks',
        path: '/admin/team/tasks',
        groupId: 'team',
        titleFa: 'کارتابل وظایف و گردش‌کار پرسنل',
        titleEn: 'Tasks',
        shortTitleFa: 'کارتابل وظایف',
        descriptionFa: 'وظایف ارجاعی به اپراتورها، داوری طرح‌ها و پیگیری استردادهای مالی',
        iconName: 'CheckSquare',
        badgeKey: 'openTasks',
      },
      {
        id: 'reports',
        path: '/admin/team/reports',
        groupId: 'team',
        titleFa: 'گزارش راندمان کاری و شیفت‌های آتلیه',
        titleEn: 'Reports',
        shortTitleFa: 'گزارش راندمان',
        descriptionFa: 'تعداد طرح‌های تاییدشده به تفکیک همکار، سرعت پاسخگویی و خطای چاپ صفر',
        iconName: 'LineChart',
        allowedRoles: ['super_admin'],
      },
      {
        id: 'administrators',
        path: '/admin/team/administrators',
        groupId: 'team',
        titleFa: 'فهرست مدیران، طراحان و اپراتورها',
        titleEn: 'Administrators',
        shortTitleFa: 'فهرست همکاران',
        descriptionFa: 'مشخصات پرسنل، نقش‌های شبیه‌سازی شده، شماره تماس داخلی و آخرین زمان ورود',
        iconName: 'UserCog',
        allowedRoles: ['super_admin'],
      },
      {
        id: 'permissions',
        path: '/admin/team/permissions',
        groupId: 'team',
        titleFa: 'ماتریس سطوح دسترسی و اختیارات (RBAC Matrix)',
        titleEn: 'Permissions',
        shortTitleFa: 'ماتریس دسترسی',
        descriptionFa: 'تنظیمات نقش‌ها (مدیر ارشد، طراح آتلیه، اپراتور تولید، مالی) و شفاف‌سازی گاردها',
        iconName: 'Key',
        allowedRoles: ['super_admin'],
      },
      {
        id: 'audit',
        path: '/admin/team/audit',
        groupId: 'team',
        titleFa: 'دفتر لاگ و حسابرسی رویدادها (Audit Logs)',
        titleEn: 'Audit',
        shortTitleFa: 'دفتر حسابرسی و لاگ',
        descriptionFa: 'رویدادهای ثبت‌شده در کارگاه، تغییرات موجودی، تغییر وضعیت سفارش و استردادها',
        iconName: 'History',
        allowedRoles: ['super_admin'],
      },
    ],
  },
  {
    id: 'system',
    titleFa: 'تنظیمات و سیستم',
    titleEn: 'System',
    iconName: 'Sliders',
    routes: [
      {
        id: 'cms',
        path: '/admin/system/cms',
        groupId: 'system',
        titleFa: 'مدیریت محتوا، بنرها و متن‌های ویترین',
        titleEn: 'CMS',
        shortTitleFa: 'مدیریت محتوا (CMS)',
        descriptionFa: 'ویرایش بنر هدر، متون تیتر کالکشن‌ها، قوانین ارسال و راهنمای سایزبندی فروشگاه',
        iconName: 'FileText',
        allowedRoles: ['super_admin'],
      },
      {
        id: 'settings',
        path: '/admin/system/settings',
        groupId: 'system',
        titleFa: 'تنظیمات عمومی فروشگاه و کارگاه',
        titleEn: 'Settings',
        shortTitleFa: 'تنظیمات عمومی',
        descriptionFa: 'نام تجاری شاه‌پوش، هزینه ثابت پست پیشتاز، سقف سفارشات روزانه و زمان تحویل',
        iconName: 'Settings',
        allowedRoles: ['super_admin'],
      },
      {
        id: 'integrations',
        path: '/admin/system/integrations',
        groupId: 'system',
        titleFa: 'درگاه‌های بانکی، پیامک و وب‌سرویس‌ها',
        titleEn: 'Integrations',
        shortTitleFa: 'اتصالات و وب‌سرویس‌ها',
        descriptionFa: 'تنظیمات درگاه سامان/به‌پرداخت، وب‌سرویس پیامکی کاوه‌نگار و وب‌هوک چاپخانه',
        iconName: 'Cpu',
        allowedRoles: ['super_admin'],
      },
      {
        id: 'health',
        path: '/admin/system/health',
        groupId: 'system',
        titleFa: 'سلامت سرویس‌ها، کش و لاگ‌های خطا',
        titleEn: 'Health/Logs',
        shortTitleFa: 'سلامت سرویس‌ها',
        descriptionFa: 'وضعیت حافظه پنهان مرورگر، اتصالات پایگاه داده محلی و هشدارهای سرور',
        iconName: 'HeartPulse',
        allowedRoles: ['super_admin'],
      },
      {
        id: 'data-explorer',
        path: '/admin/system/data-explorer',
        groupId: 'system',
        titleFa: 'جستجوگر خام داده‌ها (Read-only Data Explorer)',
        titleEn: 'Read-only Data Explorer',
        shortTitleFa: 'جستجوگر خام داده',
        descriptionFa: 'مشاهده مستقیم آبجکت‌های شبیه‌سازی شده، کلیدهای حافظه محلی و استخراج JSON',
        iconName: 'Database',
        allowedRoles: ['super_admin'],
      },
      {
        id: 'style-gallery',
        path: '/admin/system/style-gallery',
        groupId: 'system',
        titleFa: 'آزمایشگاه و گالری کامپوننت‌های دیزاین سیستم',
        titleEn: 'UI Style Gallery',
        shortTitleFa: 'گالری کامپوننت‌ها',
        descriptionFa: 'بررسی بصری تمامی توکن‌ها، فونت، جداول، فیلدها و رفتارهای واکنشی پنل مدیریت',
        iconName: 'Palette',
        allowedRoles: ['super_admin'],
      },
    ],
  },
];

// Flat list of all routes for fast lookup
export const ALL_ADMIN_ROUTES: AdminRouteDef[] = ADMIN_GROUPS.flatMap((g) => g.routes);

export const DEFAULT_ADMIN_ROUTE = ALL_ADMIN_ROUTES[0]; // '/admin/overview/dashboard'

export function findRouteByPath(path: string): AdminRouteDef | undefined {
  const cleanPath = path.split('?')[0].split('#')[0].replace(/\/+$/, '') || '/admin/overview/dashboard';
  return ALL_ADMIN_ROUTES.find((r) => r.path === cleanPath);
}
