import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import { config } from '../config';
import * as schema from './schema';
export const sqlite = new Database(config.DATABASE_PATH);
sqlite.pragma('journal_mode = WAL');
sqlite.pragma('foreign_keys = ON');
sqlite.pragma('busy_timeout = 5000');
sqlite.pragma('synchronous = FULL');
if (String(sqlite.pragma('journal_mode', { simple: true })).toLowerCase() !== 'wal') throw new Error('SQLite WAL mode could not be enabled');
if (sqlite.pragma('foreign_keys', { simple: true }) !== 1) throw new Error('SQLite foreign key enforcement is unavailable');
if (sqlite.pragma('busy_timeout', { simple: true }) !== 5000) throw new Error('SQLite busy timeout could not be configured');
if (sqlite.pragma('synchronous', { simple: true }) !== 2) throw new Error('SQLite FULL synchronous durability could not be configured');
export const db = drizzle(sqlite, { schema });
